# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MAP2-20201' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SwiftSoup'
  pod 'Alamofire', '~> 5.1'
  pod 'Elliotable'

  # Pods for MAP2-20201

end
